CREATE  DATABASE RHSENAI;

/* https://learn.microsoft.com/pt-br/training/courses/dp-900t00


Desenvolvimento de soluções em inteligência artificial - Microsoft AI-102
×
São Paulo - Brás

Presencial
Vagas: 17
Início 22/09/2025

Fim 10/10/2025

----------------------------------------------------

Fundamentos de Ciência de Dados - Google Cloud
×
São Paulo - Brás

Presencial
Vagas: 11
Início 09/08/2025

Fim 23/08/2025


------------------------------------------------------

Implantação de Serviços em Nuvem AWS - Arquiteto de Soluções Associate
×
São Paulo - Santo Amaro

Presencial
Vagas: 18
Início 08/10/2025

Fim 03/12/2025

Período
Horário de 4ª e 6ª feira
13:30 às 17:30


----------------------------------------------------------

Implementação em Big Data
×
São Paulo - Brás

Presencial
Vagas: 2
Início 09/08/2025

Fim 06/09/2025

Período
Horário
aos Sábados
09:00 às 18:00

*/

USE RHSENAI;


CREATE TABLE FUNCIONARIO (

 COD_FUNCIONARIO INT NOT NULL
,NOME VARCHAR (50)
,SALARIO DECIMAL(18,0))



BACKUP DATABASE RHSENAI TO DISK = 'D:\RHSENAI.BAK' WITH FORMAT, MEDIANAME = 'BACKUP FULL DO RHSENAI';


USE master

EXEC sp_detach_db 'RHSENAI', TRUE;


DROP DATABASE 'RHSENAI';

RESTORE DATABASE RHSENAI FROM DISK = 'D:\RHSENAI.BAK' WITH REPLACE;

USE RHSENAI;

SELECT * FROM FUNCIONARIO;

SELECT NAME,SCHEMA_ID FROM SYS.schemas;
SELECT * FROM SYS.objects;
SELECT * FROM SYS.tables;

INSERT INTO FUNCIONARIO
                       (COD_FUNCIONARIO
					  ,NOME
					  ,SALARIO) VALUES

					  (1, 'CARLOS DIAS', 3520.00),
					  (2, 'MARIA CLARA', 5600.00),
					  (3, 'ANTUNES SILVEIRA', 3520.00),
					  (4, 'SILVIO PRADO', 3120.00),
					  (5, 'ANDRE SOUZA', 4800.00)
  					  ;


					  SELECT * FROM FUNCIONARIO;

					  SELECT NOME,SALARIO 
					  FROM FUNCIONARIO;
					  
                      SELECT NOME 
					  FROM FUNCIONARIO;

					  SELECT NOME, SALARIO
					  FROM FUNCIONARIO WHERE SALARIO > 4000;


BACKUP DATABASE RHSENAI TO DISK = 'D:\RHSENAI.BAK' WITH FORMAT, MEDIANAME = 'BACKUP FULL DO RHSENAI';

INSERT INTO FUNCIONARIO
                       (COD_FUNCIONARIO
					  ,NOME
					  ,SALARIO) VALUES

					  (6, 'JOSÉ ANTONIO', 2500.00),
					  (7, 'DIAS DAVILA', 6500.00),
					  (8, 'ANDRÉ SOUZA', 1850.00),
					  (9, 'MARCOS ANDRADE',3500.00),
					  (10,'PAULA SANTOS',4200.00)
  					  ;

SELECT * FROM FUNCIONARIO;

BACKUP DATABASE RHSENAI TO DISK = 'D:\RHSENAI.BACK' WITH FORMAT, MEDIANAME = 'BACKUP FULL DO RHSENAI';

USE RHSENAI

SELECT  TOP 5* FROM FUNCIONARIO;

SELECT * FROM FUNCIONARIO ORDER BY 2 ASC;

SELECT * FROM FUNCIONARIO WHERE SALARIO >= 5000;

SELECT * FROM FUNCIONARIO WHERE COD_FUNCIONARIO >= 5 AND COD_FUNCIONARIO<= 8;

SELECT * FROM FUNCIONARIO WHERE SALARIO <2000

SELECT * FROM FUNCIONARIO WHERE SALARIO <> 2500

SELECT * FROM FUNCIONARIO WHERE SALARIO >3000 AND COD_FUNCIONARIO <5

SELECT * FROM FUNCIONARIO WHERE COD_FUNCIONARIO <=5 OR SALARIO >=6000

SELECT * FROM FUNCIONARIO WHERE NOME LIKE 'A%'

SELECT * FROM FUNCIONARIO WHERE NOME LIKE 'MARIA CLARA'

SELECT SUM(SALARIO) FOLHA FROM FUNCIONARIO

SELECT COUNT(DISTINCT COD_FUNCIONARIO) QTDE_FUCIONARIO
      ,SUM(SALARIO) FOLHA 
      ,MAX(SALARIO) MAIOR_SALARIO
      ,MIN(SALARIO) MENOR_SALARIO 
      ,AVG(SALARIO) MEDIA_SALARIO 
FROM FUNCIONARIO



SELECT 
2+6 SOMA
,20-15 SUBTRACAO
,2*4 MULTIPLICACAO
,8/2 DIVISAO


------------------------------------------------------------------------

ALTER TABLE FUNCIONARIO ADD
  DATA_NASCIMENTO DATE
 ,SEXO VARCHAR(10)
 ,ENDERECO VARCHAR(50)
 ,COD_CARGO INT
 ,CEP VARCHAR(8);


 SELECT * FROM FUNCIONARIO

 ALTER TABLE FUNCIONARIO 
 DROP COLUMN CEP;


 SELECT * FROM FUNCIONARIO


 EXEC sp_rename
 'FUNCIONARIO.COD_FUNCIONARIO','COD_FUNC','COLUMN';

 SELECT * FROM FUNCIONARIO

 ALTER TABLE FUNCIONARIO
 ALTER COLUMN SALARIO DECIMAL(18,2);

 ALTER TABLE FUNCIONARIO
 ADD CONSTRAINT PK_COD_FUNCIONARIO PRIMARY KEY (COD_FUNC);

 INSERT INTO FUNCIONARIO
 (COD_FUNC,NOME,SALARIO,DATA_NASCIMENTO,SEXO,ENDERECO,COD_CARGO)
 VALUES
 (1,'CARLOS DIAS',3520.00,'1990-12-21','MASCULINO','RUA GARDENIA NUMERO 25 - SAO PAULO - SP',2);


 CREATE TABLE CARGO( COD_CARGO INT NOT NULL,CARGO VARCHAR(50),AREA VARCHAR(50))

 INSERT INTO CARGO 
                  (COD_CARGO 
				  ,CARGO
				  ,AREA)
				  VALUES
				  (1,'ANALISTA TI','INFORMATICA'),
  				  (2,'DESIGNER GRAFICO','MARCKETING'),
  				  (3,'AUX ADMINISTRATIVO','ADMINISTRACAO'),
 				  (4,'RECEPCIONISTA','ADMINISTRACAO'),
  				  (5,'VENDEDOR','MARCKETING'),
				  (6,'PROGRAMADOR','INFORMATICA');


				  SELECT * FROM CARGO


				  ALTER TABLE CARGO ADD CONSTRAINT PK_DODIGO PRIMARY KEY (COD_CARGO); 

				  ALTER TABLE FUNCIONARIO ADD CONSTRAINT FK_CARGO FOREIGN KEY (COD_CARGO) REFERENCES CARGO(COD_CARGO);

INSERT INTO FUNCIONARIO 
                  (COD_FUNC
				  ,NOME
				  ,SALARIO)
				  VALUES
				  (900,'PEDRO JUNIOR',12000.00);


				  SELECT * FROM FUNCIONARIO

UPDATE FUNCIONARIO SET DATA_NASCIMENTO = '1985/12/21', SEXO = 'Masculino', ENDERECO ='Rua das Flores, 896, Arujá',COD_CARGO=1  WHERE COD_FUNC = 1;
UPDATE FUNCIONARIO SET DATA_NASCIMENTO = '1992/09/13', SEXO = 'Feminino', ENDERECO ='Rua Gardenia, 3600, São Paulo',COD_CARGO=4  WHERE COD_FUNC = 2;
UPDATE FUNCIONARIO SET DATA_NASCIMENTO = '1983/04/21', SEXO = 'Masculino', ENDERECO ='Rua das Rosas, 560, Arujá',COD_CARGO=2  WHERE COD_FUNC = 3;
UPDATE FUNCIONARIO SET DATA_NASCIMENTO = '1997/08/12', SEXO = 'Masculino', ENDERECO ='Rua Hermenegildo, 102, Guarulhos',COD_CARGO=1  WHERE COD_FUNC = 4;
UPDATE FUNCIONARIO SET DATA_NASCIMENTO = '2002/04/06', SEXO = 'Masculino', ENDERECO ='Rua Serra, 56, Guarulhos',COD_CARGO=2  WHERE COD_FUNC = 5;
UPDATE FUNCIONARIO SET DATA_NASCIMENTO = '1996/11/25', SEXO = 'Masculino', ENDERECO ='Rua Neto Brito, 89, São Paulo',COD_CARGO=1  WHERE COD_FUNC = 6;
UPDATE FUNCIONARIO SET DATA_NASCIMENTO = '1994/02/02', SEXO = 'Masculino', ENDERECO ='Rua das Elenice, 78, Guarulhos',COD_CARGO=5  WHERE COD_FUNC = 7;
UPDATE FUNCIONARIO SET DATA_NASCIMENTO = '1980/06/23', SEXO = 'Masculino', ENDERECO ='Rua das Flores, 1000, São Paulo',COD_CARGO=4  WHERE COD_FUNC = 8;
UPDATE FUNCIONARIO SET DATA_NASCIMENTO = '1989/07/20', SEXO = 'Masculino', ENDERECO ='Rua Grande Sul, 40, São Paulo',COD_CARGO=3  WHERE COD_FUNC = 9;
UPDATE FUNCIONARIO SET DATA_NASCIMENTO = '1990/06/12', SEXO = 'Feminino', ENDERECO ='Avenida José Teodoro, 40, Arujá',COD_CARGO=2  WHERE COD_FUNC = 10;


SELECT * FROM FUNCIONARIO
 SELECT * FROM CARGO

DELETE  FROM FUNCIONARIO WHERE COD_FUNC = 900

 BACKUP DATABASE RHSENAI TO DISK = 'D:\RHSENAI.BAK' WITH FORMAT, MEDIANAME = 'BACKUP FULL DO RHSENAI'; 

 /*-------------------------------------------07/08/2025 - AULA6-------------------------------------------*/


 RESTORE DATABASE RHSENAI FROM DISK = 'D:\RHSENAI.BAK' WITH REPLACE;

 USE RHSENAI

 BACKUP DATABASE RHSENAI TO DISK = 'D:\RHSENAI.BAK' WITH FORMAT, MEDIANAME = 'BACKUP FULL DO RHSENAI';




