
/*
use RHSENAI
*/
select * from CARGOS
select * from Funcionarios
/*
select A.cod_cargo, A.cargo, B.cod_func,
B.nome, b.salario,b.sexo
from CARGOS AS A INNER JOIN Funcionarios AS B
ON
A.COD_CARGO = B.COD_FUNC;
*/
/*
CREATE VIEW LIST_SEXO
AS SELECT COD_FUNC,NOME,SALARIO,SEXO
FROM Funcionarios
WHERE SEXO = 'MASCULINO'

*/
DROP VIEW SETOR_MARKETING

CREATE VIEW SETOR_MARKETING
AS SELECT 
A.COD_CARGO, A.AREA,
B.COD_FUNC, B.NOME, B.SALARIO, B.SEXO, B.ENDERECO
FROM CARGOS AS A INNER JOIN Funcionarios AS B
ON
A.COD_CARGO = B.COD_CARGO
WHERE AREA = 'MARKETING'

SELECT * FROM SETOR_MARKETING

CREATE VIEW CARGOS_ATIVOS AS 
SELECT A.COD_CARGO, A.CARGO,A.AREA, B.COD_FUNC,
B.NOME, B.SALARIO, B.SEXO
FROM CARGOS AS A INNER JOIN Funcionarios AS B 
ON
A.COD_CARGO = B.COD_CARGO

DROP VIEW CARGOS_ATIVOS

ALTER VIEW LIST_SEXO
AS SELECT COD_FUNC, NOME, SALARIO, SEXO
FROM Funcionarios
WHERE SEXO = 'FEMININO'


SELECT * FROM FUNC_SEXO



ALTER VIEW LIST_SEXO
RENAME TO FUNC_SEXO

EXEC sp_rename LIST_SEXO,FUNC_SEXO


DROP VIEW FUNC_SEXO

SELECT * FROM FUNC_SEXO



SELECT * FROM Funcionarios

SELECT * FROM SETOR_MARKETING

SELECT * FROM CARGOS_ATIVOS

ALTER TABLE funcionarios
ALTER COLUMN salario money

alter view carcos_ATIVOS
ADD COLUMN AREA 



select a.nome,a.sexo, b.cargo,b.area from Fucionarios a inner join CARGOS b on
a.cod_cargo = b.COD_CARGO

select a.NOME, a.SEXO, b.CARGO, b.AREA from Funcionarios a INNER JOIN CARGOS b on
a.COD_CARGO = b.COD_CARGO
select * from CARGOS