USE RHSENAI
CREATE TABLE CARGOS (
COD_CARGOS INT NOT NULL,
CARGO VARCHAR(50),
AREA VARCHAR(50) NOT NULL);
--
insert INTO CARGOS
(COD_CARGOS,CARGO,AREA)
VALUES
(1, 'ANALISTA DE TI', 'INFORMATICA'),
(2, 'DESIGNER GRÁFICO', 'MARKETING'),
(3, 'AUX.ADMINISTRATIVO', 'ADMINISTRAÇÃO'),
(4, 'RECEPCIONISTA', 'ADMINISTRAÇÃO'),
(5, 'VENDEDOR', 'MARKETING'),
(6, 'PROGRAMADOR', ' INFORMATICA');
--
use RHSENAI
SELECT * FROM CARGOS
--
USE RHSENAI
ALTER TABLE CARGOS 
ADD CONSTRAINT PK_CODIGO PRIMARY KEY (cod_cargos)
--
insert into CARGOS
(COD_CARGOS,CARGO,AREA)
VALUES
(3, 'OPERADOR CNC','manutenção');
--
select top 6 * from CARGOS;
--
SELECT DISTINCT AREA
FROM CARGOS;
--
USE RHSENAI
SELECT * FROM CARGOS
WHERE CARGO LIKE 'MARKETING'
--
alter table funcionarios 
add constraint fk_cargo
FOREIGN KEY (COD_CARGO) REFERENCES CARGOS(COD_CARGOS);