


select * from Funcionarios


CREATE TABLE CARGO(
COD_CARGO INT PRIMARY KEY NOT NULL,
CARGO VARCHAR(50) NOT NULL,
AREA VARCHAR(50) NULL
);



insert into CARGO
(COD_CARGO,CARGO,AREA)values
( 1,'ANALISTA TI', 'INFORMÁTICA'),
(2,'DESIGNER GRÁFICO','MARKETING'),
(3,'AUX,ADMINISTRATIVO','ADMINISTRAÇÃO'),
(4, 'RECEPCIONISTA','ADMINISTRAÇÃO'),
(5, 'VENDEDOR', 'MARKETING'),
(6, 'PROGRAMADOR','INFORMATICA')


insert into CARGO
(COD_CARGO,CARGO,AREA)values
( 3,'Operador CNC', 'Manutenção')

select * from CARGO



--Quantos cargos temos na empresa

select count(*) cargo from cargo;

--- Quais são as areas de atuação destes profissionais
select distinct AREA from cargo

---QUAIS SÃO AS PROFISSÕES DA AREA DE MARKETING
SELECT * FROM CARGO
WHERE AREA ='MARKETING'

--- LISTAR TODAS AS PROFISSIONAIS EM ORDEM ALFABETICA A-Z
SELECT * FROM CARGOS
ORDER BY CARGO ASC;

-- DELETANDO REGISTRO DA TABELA 
DELETE FROM CARGOS
WHERE COD_CARGO = 5


insert into CARGOS
(COD_CARGO,CARGO,AREA)values
( 5,'VENDEDOR', 'MARKTING')

-- RENOMEANDO NOME DA TABELA 

EXEC sp_rename 'CARGO', 'CARGOS';





ALTER TABLE FUNCIONARIOS
ADD CONSTRAINT FK_CARGO
FOREIGN KEY (COD_CARGO) REFERENCES CARGOS(COD_CARGO)



UPDATE Funcionarios SET DATA_NASCIMENTO = '1985/12/21', SEXO = 'M', ENDERECO = 'RUA DAS FLORES, 896, ARUJÁ',COD_CARGO = 1 WHERE COD_FUNC = 1;
UPDATE Funcionarios SET DATA_NASCIMENTO = '1992/09/13', SEXO = 'F', ENDERECO = 'RUA GARDENIA, 3600, SÃO PAULO',COD_CARGO = 4 WHERE COD_FUNC = 2;
UPDATE Funcionarios SET DATA_NASCIMENTO = '1983/04/21', SEXO = 'M', ENDERECO = 'RUA DAS ROSAS, 560, ARUJÁ',COD_CARGO = 2 WHERE COD_FUNC = 3;
UPDATE Funcionarios SET DATA_NASCIMENTO = '1997/08/12', SEXO = 'M', ENDERECO = 'RUA HERMENEGILDO, 102, GUARULHOS',COD_CARGO = 1 WHERE COD_FUNC = 4;
UPDATE Funcionarios SET DATA_NASCIMENTO = '2002/04/06', SEXO = 'M', ENDERECO = 'RUA SERRA, 56, GUARULHOS',COD_CARGO = 2 WHERE COD_FUNC = 5;
UPDATE Funcionarios SET DATA_NASCIMENTO = '1996/11/25', SEXO = 'M', ENDERECO = 'RUA NETO BRITO, 89, SÃO PAULO',COD_CARGO = 1 WHERE COD_FUNC = 6;
UPDATE Funcionarios SET DATA_NASCIMENTO = '1994/02/02', SEXO = 'M', ENDERECO = 'RUA DAS ELENICE, 78, GUARULHOS',COD_CARGO = 5 WHERE COD_FUNC = 7;
UPDATE Funcionarios SET DATA_NASCIMENTO = '1980/06/23', SEXO = 'M', ENDERECO = 'RUA DAS FLORES, 1000, SÃO PAULO',COD_CARGO = 4 WHERE COD_FUNC = 8;
UPDATE Funcionarios SET DATA_NASCIMENTO = '1989/07/20', SEXO = 'M', ENDERECO = 'RUA GRANDE SUL, 40, SÃO PAULO',COD_CARGO = 3 WHERE COD_FUNC = 9;
UPDATE Funcionarios SET DATA_NASCIMENTO = '1990/06/12', SEXO = 'F', ENDERECO = 'AVENIDA JOSÉ TEODORO, 40, ARUJÁ',COD_CARGO = 2 WHERE COD_FUNC = 10;


SELECT * FROM Funcionarios

SELECT * FROM Funcionarios
WHERE SEXO = 'M'


SELECT SUM(SALARIO) AS 'VALOR TOTAL', SEXO  FROM Funcionarios 
GROUP BY SEXO

SELECT SUM(SALARIO) AS 'VALOR TOTAL', SEXO  FROM Funcionarios 
WHERE = SEXO = 'F'
GROUP BY SEXO